[workspace]
resolver = "3"
members = ["crates/acrylius-proto", "crates/acrylius-core", "crates/acrylius-rt", "crates/acryliusd", "crates/acrylius-ffi", "crates/acrylius-linux"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
license = "MIT"
repository = "https://github.com/Vercixx/acrylius"

[workspace.dependencies]
acrylius-proto = { path = "crates/acrylius-proto" }
acrylius-core  = { path = "crates/acrylius-core" }
acrylius-rt    = { path = "crates/acrylius-rt" }
acrylius-linux = { path = "crates/acrylius-linux" }

minicbor  = { version = "2.3", features = ["alloc", "derive"] }
sha2      = { version = "0.10", default-features = false }
hkdf      = { version = "0.12", default-features = false }
snow      = "0.10"
x25519-dalek = { version = "2", features = ["static_secrets"] }
thiserror = { version = "2", default-features = false }
tracing   = "0.1"
tokio     = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "io-std", "sync", "time", "process", "signal"] }
mdns-sd   = "0.21"
anyhow    = "1"
async-trait = "0.1"
clap = { version = "4", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.9"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.9"
uniffi = "0.32"
zbus = "5.19"
wl-clipboard-rs = "0.9"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
